[package]
name = "macroquad_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.2"
itertools = "0.11.0"
ord_subset = "3.1.1"
indexmap = "2.0.0"
enum-as-inner = "0.6.0"